FROM ubuntu:latest
RUN apt-get -y update && apt-get -y install net-tools socat kmod

# docker build -t ubutil -f https://raw.githubusercontent.com/stjeong/sample_docker_script/main/dockerfile.ubutil .